before_install:
  - openssl aes-256-cbc -K $encrypted_dded3a778621_key -iv $encrypted_dded3a778621_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
  - 12
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build travis@aboni.dev:/www/landing-page
  on:
    branch: master
