export const skillsItems = {
  Dev: [
    "Javascript, HTML, CSS",
    "Nodejs, React, Alpine, Svelte, Nextjs",
    "Hugo, Gatsby, Next.js, Sapper",
    "TailwindCSS, Antd, Bulma, Bootstrap, MeterialUI",
    "Python, c#, vba, php, bash",
    "Devops, kubernetes, docker, IaaC",
    "Wordpress, WooCommerce",
    "Unity 3D, Godot Engine",
    "AI based dev, OpenAI, Langchain, Flowise, Langflow, Fooocus",
  ],
  IT: [
    "Network And Infraestructure Design, Planning and Implementation ",
    "Technical Project Management and Team Leader",
    "Technology research",
    "Router/Firewall administration",
    "Widows/Linux Server Administration",
    "Virtualization with VMWare and Proxmox",
    "Technology implementation of essential enterprise solutions.",
    "Software and Hardware Logging and monitoring",
    "Software and Hardware Tech Support",
    "Help Desk implementation and management",
    "Equipment Configuration and commisioning",
    "Cisco CCNA level: Routing and switching",
  ],
  "BI and Data": [
    "Advanced Excel",
    "Advanced PowerBI Reporting",
    "Sharepoint, Power Platform, MS List ",
    "Data Pipelines, ETL, ELT, Airbyte, Metabase",
  ],
  Misc: [
    "CCNA official course: Routing and switching",
    "English-Spanish translation specializing in computer science and technical translation",
    "Experience in Music and Audio Production, Mixing and Mastering.",
    "English: Written: Proficient, Spoken: Intermediate",
    "Spanish: Native",
  ],
};
