export const skillsItems = {
  dev: [
    "Javascript, HTML,CSS",
    "Node.js, React.js, Svelte, Mobx",
    "Hugo, Gatsby, Next.js, Sapper",
    "Antd, TailwindCSS, Bulma, Bootstrap, MeterialUI",
    "Wordpress, WooCommerce",
    "Game Development with Unity 3D and Godot Engine",
    "Python, c#, vba, excel, php",
    "Devops, kubernetes, docker, IaaC",
  ],
  it: [
    "Network And Infraestructure Design, Planning and Implementation ",
    "Technical Project Management and Team Leader",
    "Technology research",
    "Router/Firewall administration",
    "Widows/Linux Server Administration",
    "Virtualization with VMWare and Proxmox",
    "Technology implementation of essential enterprise solutions.",
    "Software and Hardware Logging and monitoring",
    "Tech Support (Software and Hardware)",
    "Equipment Configuration and commisioning",
    "Cisco CCNA level: Routing and switching",
  ],
  misc: [
    "4 Years of English-Spanish translation specializing in computer science and technical translation",
    "Successfully finished Cisco CCNA official course: Routing and switching",
    "Music and Audio Production, Mixing and Mastering.",
    "English: Written: Proficient, Spoken: Intermediate",
    "Spanish: Native",
  ],
};
